---
version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    cooldown:
      default-days: 7
    schedule:
      interval: monthly
    labels:
      - area/ci
      - kind/update
      - priority/low

  - package-ecosystem: docker
    directory: /
    cooldown:
      default-days: 7
    schedule:
      interval: monthly
    labels:
      - area/ci
      - kind/update
      - priority/medium
