---
name: Feature Request
description: File a feature request
title: '[FEATURE REQUEST] '
labels:
  - kind/feature
  - meta/needs triage
  - priority/low

body:
  - type: markdown
    attributes:
      value: |
        # Filing a report

        Thank you for participating in this project and proposing a new
        feature. **Be advised that you will most likely need to implement
        the feature you are looking for on your own due to maintainers'
        timing constraints.** If the feature is not approved, please fork
        this repository.

  - type: textarea
    id: descriptions
    attributes:
      label: Describe Your Idea
      render: Markdown
