---
name: Build Edge on Schedule

on:  # yamllint disable-line rule:truthy
  schedule:
    - cron: 0 4 1 * *

permissions:
  contents: read

jobs:
  build-images:
    name: Build Images
    uses: georglauterbach/k8s-dns/.github/workflows/generic_build.yml@main

  publish-images:
    name: Publish Images
    needs: build-images
    permissions:
      contents: read # Required to checkout the repository
      packages: write # Required to push the container image
    uses: georglauterbach/k8s-dns/.github/workflows/generic_publish.yml@main
    secrets:
      GHCR_REPOSITORY: ${{ secrets.GHCR_REPOSITORY }}
      DOCKER_REPOSITORY: ${{ secrets.DOCKER_REPOSITORY }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
