---
name: Build Edge on Schedule

on:  # yamllint disable-line rule:truthy
  schedule:
    - cron: 0 0 * * 5

permissions:
  contents: read
  packages: write

jobs:
  build-images:
    name: Build Images
    uses: georglauterbach/k8s-dns/.github/workflows/generic_build.yml@main

  publish-images:
    name: Publish Images
    needs: build-images
    uses: georglauterbach/k8s-dns/.github/workflows/generic_publish.yml@main
    with:
      cache-key: ${{ needs.build-images.outputs.build-cache-key }}
    secrets: inherit
