---
name: Build, Test & Deploy

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - Dockerfile
      - scripts/**
      - configuration/**
    tags:
      - '*.*.*'

permissions:
  contents: read
  packages: write

jobs:
  build-image:
    name: Build Image
    uses: georglauterbach/k8s-dns/.github/workflows/generic_build.yml@main

  publish-images:
    name: Publish Image
    needs: [build-image]
    uses: georglauterbach/k8s-dns/.github/workflows/generic_publish.yml@main
    secrets: inherit
