---
name: Build the Container Image

on: # yamllint disable-line rule:truthy
  workflow_call:

permissions:
  contents: read

jobs:
  build-image:
    name: Build
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64
          push: false
          provenance: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
