---
name: Publish the DMS Container Image

on: # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      cache-key:
        required: true
        type: string

permissions:
  contents: read
  packages: write

jobs:
  publish-images:
    name: Publish
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Prepare tags
        id: prep
        uses: docker/metadata-action@v5.7.0
        with:
          images: |
            ${{ secrets.GHCR_REPOSITORY }}
            ${{ secrets.DOCKER_REPOSITORY }}
          tags: |
            type=edge,branch=main
            type=semver,pattern={{major}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}.{{minor}}.{{patch}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.6.0
        with:
          platforms: arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.10.0

      # Try get the cached build layers from a prior `generic_build.yml` job.
      # NOTE: Until adopting `type=gha` scoped cache exporter (in `docker/build-push-action`),
      # only AMD64 image is expected to be cached, ARM images will build from scratch.
      - name: Retrieve image build from build cache
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: cache-buildx-${{ inputs.cache-key }}
          restore-keys: |
            cache-buildx-

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Acquire the image version
        id: get-version
        shell: bash
        run: echo "version=$(<VERSION)" >>"${GITHUB_OUTPUT}"

      - name: Build and publish images
        uses: docker/build-push-action@v6.17.0
        with:
          context: .
          build-args: |
            BUILD_VCS_REFERENCE=${{ github.sha }}
            BUILD_VCS_VERSION=${{ steps.get-version.outputs.version }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.prep.outputs.tags }}
          cache-from: type=local,src=/tmp/.buildx-cache
