---
name: Publish the DMS Container Image

on: # yamllint disable-line rule:truthy
  workflow_call:

permissions:
  contents: read
  packages: write

jobs:
  publish-images:
    name: Publish
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Prepare tags
        id: prep-tags
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ secrets.GHCR_REPOSITORY }}
            ${{ secrets.DOCKER_REPOSITORY }}
          tags: |
            type=edge,branch=main
            type=semver,pattern={{major}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}.{{minor}}.{{patch}}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push images
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          build-args: |
            VCS_VERSION=${{ github.ref_type == 'tag' && github.ref_name || 'edge' }}
            VCS_REVISION=${{ github.sha }}
          push: true
          provenance: true
          tags: ${{ steps.prep-tags.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max